<?php

declare(strict_types=1);

/**
 * @file
 * Provides an appointment entity type.
 */

use Drupal\appointment\Entity\AppointmentInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function appointment_theme(): array {
  return [
    'agency' => ['render element' => 'elements'],
    'appointment' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for agency templates.
 *
 * Default template: agency.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the agency information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_agency(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for appointment templates.
 *
 * Default template: appointment.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the appointment information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_appointment(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave() for appointment entities.
 */
function appointment_appointment_presave(AppointmentInterface $appointment) {
  if ($appointment->isNew() && empty($appointment->get('reference')->value)) {
    // RDV-2025-17032614-A3F2 (year-timestamp-random)
    $year = date('Y');
    $timestamp = date('dmHis'); // 17032614 = 17 March 26:14
    $random = strtoupper(substr(md5(uniqid((string) mt_rand(), true)), 0, 4));
    $reference = "RDV-{$year}-{$timestamp}-{$random}";
    
    $appointment->set('reference', $reference);
  }
}